version: 2
jobs:
  build:
    docker:
      - image: cimg/node:14.17.0

    working_directory: /tmp/use-object-memo

    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}

      - run: npm install --no-shrinkwrap

      - save_cache:
          key: v1-dependencies-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - run: npm run lint
      - run: npm test
      - run: npm run build
